Adding metadata and checkout options support to invoice client.
woutersamaey/btcpayserver-greenfield-php-client pull request #7
Opened 2021-07-15 12:03 UTC by ndeet

2021-07-15 12:55 UTC, woutersamaey requested changes

2021-07-15 12:55 UTC, woutersamaey commented on src/Client/Invoice.php
> +        ?string $orderId = '',
Why not default to NULL? Empty string is so ugly.

2021-07-15 12:55 UTC, woutersamaey commented on examples/create_invoice.php
> +      'itemCode' => 'Can SKU or item number',
Add word "be"

2021-07-15 12:55 UTC, woutersamaey commented on src/Client/Invoice.php
> +     * @param string                                           $storeId
Do we need all these @param?
We have type hinting saying the same thing.

2021-07-15 12:55 UTC, woutersamaey commented on src/Client/Invoice.php
> +        ?array $metaData = [],
I'd prefer NULL over [], but this is nit-pick.

2021-07-15 12:55 UTC, woutersamaey commented on src/Client/Invoice.php
> +            $metaDataMerged['orderId'] = $orderId;
Should we throw an exception if a previous value was already there? You may be overwriting something without the dev realizing...

2021-07-15 12:55 UTC, woutersamaey commented on src/Client/Invoice.php
> +            $metaDataMerged['buyerEmail'] = $customerEmail;
Should we throw an exception if a previous value was already there? You may be overwriting something without the dev realizing...

2021-07-15 12:55 UTC, woutersamaey commented on src/Client/Invoice.php
> +    public function getInvoice(
Why all these newlines? If this the PSR-12 ? It looks ugly for such a short method.
Nit-pick... sorry.

2021-07-15 12:55 UTC, woutersamaey commented on src/Client/InvoiceCheckoutOptions.php
> +        $this->speedPolicy = $speedPolicy;
Use constants and check values. Throw InvalidArgumentException

2021-07-15 12:55 UTC, woutersamaey commented on src/Client/InvoiceCheckoutOptions.php
> +     * @return InvoiceCheckoutOptions
PHP doc is meaningless. Should we remove?

2021-07-15 12:55 UTC, woutersamaey commented on src/Client/InvoiceCheckoutOptions.php
> +    ): InvoiceCheckoutOptions {
I think we can do `: self` instead of `: InvoiceCheckoutOptions`. Is that supported?

2021-07-15 12:55 UTC, woutersamaey commented on src/Client/InvoiceCheckoutOptions.php
> +    public function setRedirectAutomatically(
Lots of newlines again

2021-07-15 12:55 UTC, woutersamaey commented on src/Client/Invoice.php
> +            'checkout' => $checkoutOptions ? Formatter::objectToArrayNoEmpty($checkoutOptions) : new \stdClass()
Why use this or StdClass?
Does it have to be an object?
can be NULL too? Or just return the exact type?

2021-07-15 13:01 UTC, ndeet commented on src/Client/Invoice.php
> +        ?string $orderId = '',
I would too, just thought you I will keep the type as you nitpicked my `if (!empty($string))` in the other PR 😛

2021-07-15 13:06 UTC, woutersamaey commented on src/Client/Invoice.php
> +        ?string $orderId = '',
I don't see how that relates really.
`NULL` = I don't have a value or does not apply.
empty string = I have a value, and it happens to be empty.

So I do see a difference.

We should not set to empty string if the user does not care about this field.

That's my reasoning. Has nothing to do with `empty()` functions :stuck_out_tongue: 
Sorry about that nitpick though :sweat_smile:

2021-07-15 13:07 UTC, ndeet commented on src/Client/Invoice.php
> +     * @param string                                           $storeId
true, was added by PHPStorm and adds no value if we do not have to say more about them

2021-07-15 13:09 UTC, ndeet commented on src/Client/Invoice.php
> +        ?array $metaData = [],
yes, fine with that too

2021-07-15 13:09 UTC, woutersamaey commented on src/Client/Invoice.php
> +     * @param string                                           $storeId
Yeah, PHPStorm is like that. I remove those lines manually every time.

2021-07-15 13:09 UTC, ndeet commented on src/Client/Invoice.php
> +        ?array $metaData = [],
although, `NULL` or `null`?

2021-07-15 13:10 UTC, ndeet commented on src/Client/Invoice.php
> +            $metaDataMerged['orderId'] = $orderId;
Ok a good idea I think, so we need a check for those two metadata keys and throw an exception.

2021-07-15 13:11 UTC, ndeet commented on src/Client/Invoice.php
> +    public function getInvoice(
Yes PSR-12, also not a huge fan tbh

2021-07-15 13:18 UTC, woutersamaey commented on src/Client/Invoice.php
> +        ?array $metaData = [],
Sorry, I usually write NULL because of MySQL, but I think in PHP it does not matter or `null` is more common?

2021-07-15 13:18 UTC, woutersamaey commented on src/Client/Invoice.php
> +            $metaDataMerged['orderId'] = $orderId;
I'd use `array_key_exists` for this, not `isset()` :wink:

2021-07-15 21:57 UTC, ndeet commented on src/Client/Invoice.php
> +            'checkout' => $checkoutOptions ? Formatter::objectToArrayNoEmpty($checkoutOptions) : new \stdClass()
`null` works too, passing empty array did throw error on the api side as the JSON was outputting an array when there should be an empty object

2021-07-15 21:58 UTC, ndeet commented on src/Client/InvoiceCheckoutOptions.php
> +    public function setRedirectAutomatically(
yeah because of return type full class name, replaced with `self` like you suggested

2021-07-15 21:59 UTC, ndeet commented on src/Client/InvoiceCheckoutOptions.php
> +    ): InvoiceCheckoutOptions {
was generated by PHPStorm, agree, `self` is nicer

2021-07-15 21:59 UTC, ndeet commented on src/Client/InvoiceCheckoutOptions.php
> +     * @return InvoiceCheckoutOptions
yes, also generated by PHPStorm, removed them

2021-07-15 22:30 UTC, ndeet commented on src/Client/InvoiceCheckoutOptions.php
> +        $this->speedPolicy = $speedPolicy;
Not sure what benefit we have with constants here but I see what you mean as it is an Enum in the API. So maybe have an array with allowed values and check for that is enough. Adding a constants for now.

2021-07-16 09:33 UTC, woutersamaey commented on src/Client/InvoiceCheckoutOptions.php
> +    public const HIGHSPEED = 'HighSpeed';
Can we use `SPEED_LOW` in this format? That way all "speed" related constants start the same.
If some other constants get added, it would be easier to navigate.
It's quite common to put the type first and then what it's about.

2021-07-16 09:35 UTC, woutersamaey commented on src/Client/InvoiceCheckoutOptions.php
> +    public function create(
Should we make this static? Currently you need to create the class first and then call `->create()` again? It seams a bit weird.

2021-07-16 09:45 UTC, woutersamaey reviewed
Final comments. Very close now!

2021-07-16 09:45 UTC, woutersamaey commented on src/Client/Invoice.php
> +            'checkout' => $checkoutOptions ? Formatter::objectToArrayNoEmpty($checkoutOptions) : null
I think I prefer `$checkoutOptions->toArray()`. Isn't that easier?
The formatter seams a bit overkill. Also, it's not really formatting, is it? If you want to keep it, I'd maybe call it a `Converter`?

2021-07-16 09:45 UTC, woutersamaey commented on src/Util/Formatter.php
> +            $array[trim(str_replace('*', '', $k))] = $v;
Why not use `ltrim($k, '* ')`  to trim spaces and asterisks form the left side only?

2021-07-16 22:01 UTC, ndeet commented on src/Client/InvoiceCheckoutOptions.php
> +    public const HIGHSPEED = 'HighSpeed';
yes, I had `SPEED_LOWSPEED` before comitting but thought it would be a bit redundant, they format you suggested makes more sense 👍

2021-07-16 22:02 UTC, ndeet commented on src/Client/InvoiceCheckoutOptions.php
> +    public function create(
We can yes, do you suggest to make the whole class static or only the function which then instantiates the class to have props available?

2021-07-16 22:05 UTC, ndeet commented on src/Client/Invoice.php
> +            'checkout' => $checkoutOptions ? Formatter::objectToArrayNoEmpty($checkoutOptions) : null
Maybe some premature optimization on my end. I thought a generic class to array converter with dropping all empty props may be helpful for other endpoints too. I assumed there will be similar cases but not sure if there are any. So maybe we go with toArray() first and refactor it out if at least one other use case needs this.

2021-07-16 22:19 UTC, ndeet commented on src/Util/Formatter.php
> +            $array[trim(str_replace('*', '', $k))] = $v;
tried a bit but it seems to not remove unicode spaces that happen to be there before and after the asterisk, e.g. `"\u0000*\u0000keyname"`

2021-07-17 19:18 UTC, woutersamaey commented on src/Util/Formatter.php
> +            $array[trim(str_replace('*', '', $k))] = $v;
We should be able to solve this, but it is weird.
I do feel we should maybe use reflection for this, but I guess it will have lower performance and maybe also some challenges. What do you think?

2021-07-17 19:55 UTC, ndeet commented on src/Util/Formatter.php
> +            $array[trim(str_replace('*', '', $k))] = $v;
It is solved right now and works. I did not find a better solution to the use case here: "output all properties of an object and skip empty ones". Removing the whitespace and asterisk is only needed because of the protected properties.

1) keep as is
2) make all props public (no need to remove whitespace + asterisk, just check if value there or not; then also `get_object_vars()` can be used)
3) use Reflection, not sure if worth figuring it out? Performance should imo [not be an issue](https://stackoverflow.com/questions/294582/php-5-reflection-api-performance) as we have not many iterations and just call it once per request? 
4) remove the class and only do an array similar to metadata 
5) maybe there is a straight forward way I do not know

2021-07-17 20:46 UTC, woutersamaey commented on src/Util/Formatter.php
> +            $array[trim(str_replace('*', '', $k))] = $v;
Ok, so should we merge now?

2021-07-17 20:46 UTC, woutersamaey commented on src/Util/Formatter.php
> +            $array[trim(str_replace('*', '', $k))] = $v;
We can revisit this later to be honest. Just wanna move ahead with the Magento 2 plugin.

2021-07-17 20:47 UTC, woutersamaey commented on src/Client/InvoiceCheckoutOptions.php
> +    public function create(
I was thinking only the function which then instantiates the class.

2021-07-19 06:30 UTC, woutersamaey commented on src/Util/Formatter.php
> +            $array[trim(str_replace('*', '', $k))] = $v;
I did some testing and figured out the best way to do this:
```
$array = [];
foreach ((array) $obj as $k => $v) {
    $separator = "\0";
    $k = rtrim($k, $separator);
    
    $lastIndex = strrpos($k, $separator);
    if($lastIndex !== false){
        $k = substr($k, $lastIndex +1);
    }
    $array[$k] = $v;
}
```

2021-07-19 18:40 UTC, woutersamaey approved these changes

2021-07-19 19:12 UTC, ndeet commented on src/Util/Formatter.php
> +            $array[trim(str_replace('*', '', $k))] = $v;
Thanks removed Formatter class as discussed and added your suggestion to InvoiceCheckoutOptions as `toArray()` method.

2021-07-20 06:55 UTC, ndeet commented on src/Client/InvoiceCheckoutOptions.php
> +    public function create(
I have made this change yesterday. So we should be ready.

2021-07-20 07:37 UTC, merged